"""Installation and removal of the global Git hook dispatcher."""

from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Optional

from .paths import AppPaths
from .utils import WteError

# A dispatcher is installed for each common client-side hook. Most only chain
# an existing hook; post-checkout additionally invokes wte.
HOOK_NAMES = (
    "applypatch-msg",
    "pre-applypatch",
    "post-applypatch",
    "pre-commit",
    "pre-merge-commit",
    "prepare-commit-msg",
    "commit-msg",
    "post-commit",
    "pre-rebase",
    "post-checkout",
    "post-merge",
    "pre-push",
    "pre-auto-gc",
    "post-rewrite",
    "post-index-change",
    "sendemail-validate",
    "reference-transaction",
)


def _git_config(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run(
        ["git", "config", "--global", *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    if check and result.returncode != 0:
        raise WteError(result.stderr.strip() or "git config failed")
    return result


def current_hooks_path() -> Optional[str]:
    """Return the raw global core.hooksPath, if configured."""
    result = _git_config("--get", "core.hooksPath", check=False)
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _write_state(path: Path, state: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".hooks-state-", dir=path.parent)
    temp_path = Path(temporary)
    try:
        with os.fdopen(descriptor, "w") as handle:
            json.dump(state, handle, indent=2, sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temp_path, 0o600)
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


def _read_state(paths: AppPaths) -> Dict[str, Any]:
    if not paths.hooks_state.exists():
        return {}
    try:
        raw = json.loads(paths.hooks_state.read_text() or "{}")
    except (OSError, json.JSONDecodeError) as exc:
        raise WteError(f"cannot read hook state {paths.hooks_state}: {exc}") from exc
    if not isinstance(raw, dict):
        raise WteError(f"hook state must be an object: {paths.hooks_state}")
    return raw


def resolve_wte_executable() -> Path:
    """Resolve an absolute executable path suitable for GUI-launched Git hooks."""
    candidate = shutil.which("wte")
    if candidate:
        return Path(candidate).resolve()
    argv0 = Path(sys.argv[0])
    if argv0.exists():
        return argv0.resolve()
    raise WteError("cannot locate the wte executable; install it before installing hooks")


def _dispatcher_script(executable: Path, previous: Optional[str]) -> str:
    executable_value = shlex.quote(str(executable))
    previous_value = shlex.quote(previous or "")
    return f'''#!/usr/bin/env bash
# Generated by wte. Re-run `wte init` instead of editing this file.
set -u

HOOK_NAME="$(basename "$0")"
WTE_EXECUTABLE={executable_value}
PREVIOUS_HOOKS_PATH={previous_value}

if [[ "$HOOK_NAME" == "post-checkout" ]]; then
  "$WTE_EXECUTABLE" _hook "$@" || true
fi

# Preserve a hooksPath that existed before wte was installed.
if [[ -n "$PREVIOUS_HOOKS_PATH" ]]; then
  if [[ "$PREVIOUS_HOOKS_PATH" = /* ]]; then
    CHAIN_TARGET="$PREVIOUS_HOOKS_PATH/$HOOK_NAME"
  else
    CHAIN_TARGET="$PWD/$PREVIOUS_HOOKS_PATH/$HOOK_NAME"
  fi
  if [[ -x "$CHAIN_TARGET" ]]; then
    exec "$CHAIN_TARGET" "$@"
  fi
fi

# Fall back to the repository's native hook directory.
COMMON="$(git rev-parse --git-common-dir 2>/dev/null)" || exit 0
LOCAL="$COMMON/hooks/$HOOK_NAME"
if [[ -x "$LOCAL" ]]; then
  DISPATCH_DIR="$(cd "$(dirname "$0")" && pwd)"
  LOCAL_DIR="$(cd "$(dirname "$LOCAL")" && pwd)"
  if [[ "$LOCAL_DIR/$HOOK_NAME" != "$DISPATCH_DIR/$HOOK_NAME" && "$LOCAL_DIR/$HOOK_NAME" != "$DISPATCH_DIR/_dispatch" ]]; then
    exec "$LOCAL" "$@"
  fi
fi
exit 0
'''


def install_hooks(paths: AppPaths) -> Path:
    """Install the global dispatcher without silently replacing another manager."""
    paths.ensure()
    target = str(paths.hooks)
    current = current_hooks_path()
    legacy = str(Path.home() / ".config" / "git-projects" / "hooks")

    previous: Optional[str] = None
    if current and Path(os.path.expanduser(current)).resolve() != paths.hooks.resolve():
        if Path(os.path.expanduser(current)).resolve() == Path(legacy).resolve():
            # This is the pre-open-source version of wte, not an independent manager.
            previous = None
        else:
            raise WteError(
                f"core.hooksPath is already set to {current!r}; wte did not change it"
            )
    elif paths.hooks_state.exists():
        previous_raw = _read_state(paths).get("previous_hooks_path")
        previous = str(previous_raw) if previous_raw else None

    executable = resolve_wte_executable()
    paths.hooks.mkdir(parents=True, exist_ok=True)
    dispatcher = paths.hooks / "_dispatch"
    dispatcher.write_text(_dispatcher_script(executable, previous))
    dispatcher.chmod(0o755)

    for name in HOOK_NAMES:
        hook = paths.hooks / name
        if hook.is_symlink() or hook.exists():
            if hook.is_dir() and not hook.is_symlink():
                raise WteError(f"cannot replace hook directory: {hook}")
            hook.unlink()
        hook.symlink_to("_dispatch")

    _write_state(
        paths.hooks_state,
        {
            "previous_hooks_path": previous,
            "installed_hooks_path": target,
            "wte_executable": str(executable),
        },
    )
    _git_config("core.hooksPath", target)
    return dispatcher


def uninstall_hooks(paths: AppPaths) -> Optional[str]:
    """Remove wte's dispatcher and restore the previous global hooksPath."""
    state = _read_state(paths)
    previous_raw = state.get("previous_hooks_path")
    previous = str(previous_raw) if previous_raw else None
    current = current_hooks_path()
    if current and Path(os.path.expanduser(current)).resolve() == paths.hooks.resolve():
        if previous:
            _git_config("core.hooksPath", previous)
        else:
            _git_config("--unset", "core.hooksPath", check=False)
    if paths.hooks.exists():
        shutil.rmtree(paths.hooks)
    if paths.hooks_state.exists():
        paths.hooks_state.unlink()
    return previous


def hooks_status(paths: AppPaths) -> Dict[str, Any]:
    """Return current installation details for human-readable reporting."""
    state = _read_state(paths)
    current = current_hooks_path()
    installed = bool(current) and Path(os.path.expanduser(current)).resolve() == paths.hooks.resolve()
    return {
        "installed": installed,
        "current_hooks_path": current,
        "expected_hooks_path": str(paths.hooks),
        "previous_hooks_path": state.get("previous_hooks_path"),
        "wte_executable": state.get("wte_executable"),
    }
