"""Projection of ports, local secrets, and setup commands into a worktree."""

from __future__ import annotations

import os
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from string import Template
from typing import Any, Dict, List, Optional

from .config import load_port_pool
from .paths import AppPaths
from .profiles import Profile, find_profile
from .registry import (
    allocate_ports,
    load_registry,
    prune_registry,
    registry_lock,
    save_registry,
)
from .utils import WteError, expand_profile_path, log, safe_worktree_target

@dataclass(frozen=True)
class ApplyResult:
    """Details of a successful profile projection."""

    profile: str
    root: Path
    ports: Dict[str, int]


def render_template(body: str, ports: Dict[str, int]) -> str:
    """Replace profile port variables such as ``${frontend}``."""
    try:
        return Template(body).substitute({key: str(value) for key, value in ports.items()})
    except (KeyError, ValueError) as exc:
        raise WteError(f"cannot render port template: {exc}") from exc


def _secret_entries(profile: Profile) -> List[Dict[str, Any]]:
    raw = profile.get("secrets") or []
    return [item for item in raw if isinstance(item, dict)] if isinstance(raw, list) else []


def apply_secrets(profile: Profile, root: Path) -> None:
    """Replace configured targets with symlinks to existing local secret files."""
    for entry in _secret_entries(profile):
        source_raw = str(entry.get("source") or "").strip()
        target_raw = str(entry.get("target") or "").strip()
        if not source_raw or not target_raw:
            continue
        source = expand_profile_path(source_raw, profile).resolve()
        target = safe_worktree_target(root, target_raw)
        if not source.is_file():
            log(f"secret skipped; source does not exist: {source}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.is_symlink() or target.exists():
            if target.is_dir() and not target.is_symlink():
                raise WteError(f"secret target is a directory: {target}")
            target.unlink()
        target.symlink_to(source)


def apply_writes(profile: Profile, root: Path, ports: Dict[str, int]) -> None:
    """Render complete generated files declared by the profile."""
    writes = profile.get("writes") or []
    if not isinstance(writes, list):
        raise WteError(f"profile {profile.get('name')} has an invalid writes section")
    for spec in writes:
        if not isinstance(spec, dict) or not spec.get("path"):
            raise WteError(f"profile {profile.get('name')} has an invalid write entry")
        target = safe_worktree_target(root, str(spec["path"]))
        body = render_template(str(spec.get("body") or ""), ports)
        if target.is_symlink():
            target.unlink()
        target.parent.mkdir(parents=True, exist_ok=True)
        header = str(spec.get("header") or "# Generated by wte; changes will be overwritten.\n")
        payload = header + body
        target.write_text(payload if payload.endswith("\n") else payload + "\n")


def _init_entries(profile: Profile) -> List[Dict[str, Any]]:
    raw = profile.get("init") or []
    return [item for item in raw if isinstance(item, dict)] if isinstance(raw, list) else []


def run_initializers(profile: Profile, root: Path) -> None:
    """Start missing dependency setup tasks without blocking Git checkout."""
    for index, item in enumerate(_init_entries(profile)):
        command = str(item.get("command") or "").strip()
        cwd_raw = str(item.get("cwd") or "").strip()
        if not command or not cwd_raw:
            log(f"initializer skipped; command and cwd are required: {item}")
            continue
        cwd = expand_profile_path(cwd_raw, profile, root=root).resolve()
        if not cwd.is_dir():
            log(f"initializer skipped; directory does not exist: {cwd}")
            continue
        skip_if = item.get("skip_if")
        if skip_if:
            marker = expand_profile_path(str(skip_if), profile, root=cwd)
            if marker.exists():
                continue
        log_path = Path(tempfile.gettempdir()) / f"wte-init-{os.getpid()}-{index}.log"
        output = log_path.open("a")
        try:
            subprocess.Popen(
                ["bash", "-lc", command],
                cwd=str(cwd),
                stdout=output,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        finally:
            output.close()
        log(f"initializer started: {command} -> {log_path}")


def apply_worktree(
    paths: AppPaths,
    root: Path,
    setup: bool = False,
) -> Optional[ApplyResult]:
    """Apply the matching profile to one worktree.

    An unmatched repository is intentionally a no-op so the global checkout
    hook remains safe for every Git repository on the machine.
    """
    root = root.resolve()
    profile = find_profile(paths, root)
    if profile is None:
        return None

    pool = load_port_pool(paths)
    with registry_lock(paths):
        registry = prune_registry(load_registry(paths))
        block_start, ports = allocate_ports(profile, root, registry, pool)

        # Keep allocation and projection in one short transaction. If writing
        # fails, no registry entry is committed and the reconciler can retry.
        apply_secrets(profile, root)
        apply_writes(profile, root, ports)
        registry[str(root)] = {
            "profile": profile["name"],
            "file": Path(profile.get("_file") or "").name,
            "block_start": block_start,
            "ports": ports,
        }
        save_registry(paths, registry)

    if setup:
        run_initializers(profile, root)
    return ApplyResult(str(profile["name"]), root, ports)


def print_apply_result(result: ApplyResult) -> None:
    """Print a compact, stable summary for interactive use and hook logs."""
    endpoints = "  ".join(
        f"{name}=http://127.0.0.1:{port}" for name, port in result.ports.items()
    )
    print(f"[wte] profile={result.profile}")
    print(f"[wte] root={result.root}")
    print(f"[wte] {endpoints}")
